# Site settings
title: ICPS 2016
email: info@icps2016.com
description: > # this means to ignore newlines until "baseurl:"
  the website for the International Conference for Physics Students 2016 - Malta
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://icps2016.com" # the base hostname & protocol for your site
twitter_username: icps2016
facebook_username: icps2016
github_username:  norbertbonnici
permalink: /:categories/:title.html

# Build settings
markdown: kramdown
highlighter: pygments
